### ISSUE TITLE
Syntaxe des deux points

### ISSUE THREAD

**Issue by kylekatarnls** [simonc/vfsvp.fr#11]
Bonjour,

A contrario de l'anglais, les deux points en français sont précédés d'un espace. La ponctuation n'est donc pas correcte dans "Source: lien", il faut écrire "Source : lien". Pour corriger à la volée les précédents articles, il faudrait ajouter un filtre (comme ici : https://github.com/imathis/octopress/blob/master/plugins/octopress_filters.rb). Pour les corriger définitivement, une migration de repeuplement.

Cordialement,

**Comment by simonc** [comment]
Bonjour,

Effectivement c'est une faute d'inattention, il s'agit même d'un espace insécable pour être exact :)
Je ne vais cependant pas corriger le problème car VFsvp n'est plus maintenu. Le articles vont petit à petit migrer vers le blog de Tinci sur http://tinci.fr/blog.

Merci.
Cordialement,
